<form action="/login" method="POST">
    <div class="form-group mb-3">
        <label for="user_phone" class="form-label">Phone</label>
        <input id="user_phone" type="phone" name="user[phone]" class="form-control" placeholder="Enter phone">
    </div>
    <div class="form-group mb-3">
        <label for="user_password" class="form-label">Senha</label>
        <input id="user_password" type="password" name="user[password]" class="form-control" placeholder="Password">
    </div>
    <div class="d-grid">
        <input type="submit" class="btn btn-primary btn-block" value="Login">
    </div>
</form>

