<div class="container mt-4">
        <?php
          $pets = $paginator->registers();
          $i = 1;
          foreach($pets as $pet):
        ?>
          <div class="card container flex-sm-row py-3 mb-3">
            
              <?php if (isset($pet->photo_url)) { ?>
                  <div class="col-12 col-sm-3">
                    <img class="img-fluid" src="<?= '/assets/uploads/' . $pet->photo_url?>"/>
                  </div>
              <?php } else {?>
                  <div class="col-12 col-sm-3">
                    <img class="img-fluid" src="/assets/images/pet_default.png"/>
                  </div>
              <?php }?>

                <div class="col-12 col-sm">
                  <h4 ><?= $pet->name ?></h4>
                  <div class="container grid"> 
                    <p class="col "><?= $pet->specie ?? '' ?></p>
                    <div class="d-flex flex-column flex-sm-row justify-content-between gap-5">
                      <?php if (!in_array($pet->breed, ['', null])){ ?>
                        <p class=" px-1 flax-grow-1">
                          <span class="text-muted">raça: </span>
                          <?= $pet->breed?>
                        </p>
                      <?php } ?>
                      <?php if (!in_array($pet->birth_date, ['', null])){ ?>
                        <p class=" px-1 flax-grow-1">
                          <span class="text-muted">nacido(a): </span>
                          <?= $pet->birth_date?>
                        </p>
                      <?php } ?>
                    </div>
                  </div>

                </div>

                <div class="col-12 col-sm-3  d-flex flex-column gap-5 px-0 justify-content-around">
                    <div class="my-0">
                        <form  action="/my/pets/delete/<?= $pet->id ?>" method="POST">
                            <input type="hidden" id="_method" name="_method" value="DELETE" />
                            <input 
                                class="btn btn-danger btn-block" 
                                type="submit" 
                                id="delete-<?= $pet->id?>"
                                value="delete"
                               >
                                 
                        </form>
                    </div>
                    <div class="my-0">
                        <a 
                        class="btn btn-primary btn-block"
                        id="edit-<?= $pet->id?>" 
                        href="/my/pets/edit/<?= $pet->id ?>">
                          edite
                        </a>
                    </div>
                </div>

            </div>
        <?php endforeach; ?>
    <div class="d-grid">
        <a class="btn btn-primary btn-block" href="/my/pets/new">new</a>
    </div>
    <?php require  __DIR__ . '/../paginator/_pages.phtml' ?>
</div>
