<?php $flash =  isset($flash) ? $flash : \Lib\FlashMessage::get(); ?>
<div class="container fixed-top mt-4">
    <?php if (isset($flash['danger'])) : ?>
            <p class="alert alert-danger mb-2 fade show loadbar" role="alert">
                <?= $flash['danger'] ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </p>
    <?endif; ?>
    <?php if (isset($flash['success'])) :?>
            <p class="alert alert-success mb-2 fade show loadbar" role="alert">
                <?= $flash['success'] ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </p>
    <?php endif; ?>
</div>

