<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?? 'PetAgenda'?>></title>
    
    <link rel="stylesheet" href="/assets/css/lib/bootstrep.min.css"
    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body>
    <main class="container-fluid">

        <?php require '_flash_message.phtml'; ?>

        <header class="mb-3">
            <h1>
                <?= $title ?>
            </h1>
        </header>

        <?php require $view ?>

    </main>
    <script src="/assets/js/lib/jquery.mask.min.js"></script>
    <script src="/assets/js/lib/jquery-3.3.1.slim.min.js"></script>
    <script src="/assets/js/lib/popper.min.js"></script>
    <script src="/assets/js/lib/bootstrap.min.js"></script>
    <script src="/assets/js/application.js"></script>
</body>

</html>
